{{- if .Values.usernameService.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "username-checker.fullname" . }}-username-service
  labels:
    {{- include "username-checker.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "username-checker.fullname" . }}-username-service
  minReplicas: {{ .Values.usernameService.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.usernameService.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.usernameService.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
