apiVersion: v1
kind: Service
metadata:
  name: {{ include "username-checker.fullname" . }}-username-service
  labels:
    {{- include "username-checker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.usernameService.service.type }}
  ports:
  - port: {{ .Values.usernameService.service.port }}
    targetPort: 8081
    name: http
  selector:
    {{- include "username-checker.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: username-service
