apiVersion: v1
kind: Service
metadata:
  name: {{ include "username-checker.fullname" . }}-redis
  labels:
    {{- include "username-checker.labels" . | nindent 4 }}
spec:
  ports:
    - name: "6379"
      port: {{ .Values.redis.service.port }}
      targetPort: 6379
  selector:
    {{- include "username-checker.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
