apiVersion: v1
kind: Service
metadata:
  name: {{ include "username-checker.fullname" . }}-cassandra
  labels:
    {{- include "username-checker.labels" . | nindent 4 }}
spec:
  ports:
  - port: 9042
    name: cql
  - port: 7000
    name: intra-node
  clusterIP: None
  selector:
    {{- include "username-checker.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: cassandra
