apiVersion: v1
kind: Service
metadata:
  name: username-service
  labels:
    app: username-service
spec:
  type: LoadBalancer # Defaulting to LoadBalancer for ease of access, standard k8s might use ClusterIP
  ports:
  - port: 8081
    targetPort: 8081
    name: http
  selector:
    app: username-service
